### ISSUE TITLE
403 on a non protected method

### ISSUE THREAD

**Issue by raffaelespazzoli** [quarkiverse/quarkus-zanzibar#8]
I have a service with some methods that are protected by openfga annotations and some that are not. I'm getting 403 on a non protected method. That should not be possible.
Here is my method:
```java
  @GET
  @Produces(MediaType.TEXT_PLAIN)
  @Path("specialQuery")
  public String listSpecialquery() {

      String[] returnedItems = new String[]{"item:item1","item:item2","item:item3","item:item4"};
      List<String> filteredItems=Multi.createFrom().items(returnedItems).filter(new Predicate<String>() {
        @Override
        public boolean test(String t) {
          System.out.println("before: "+t);
          boolean result=authModelClient.check(new TupleKey(t, "view", securityContext.getUserPrincipal().getName()),null).await().atMost(Duration.ofSeconds(1));
          System.out.println("after: "+t);
          return result;
        }
      }).collect().asList().await().atMost(Duration.ofSeconds(5));
      
      return "Access granted to items: "+filteredItems;
```

**Comment by kdubb** [comment]
The interceptor currently assumes all methods need some authorization annotation.

To allow a public method currently you can use `FGARelation(FGARelation.ANY)`.

**Comment by kdubb** [comment]
I'm thinking we should change the current behavior in two ways:

1. Add a configuration enables or disable "global" authorization. With it enabled it would mean it works as it does now, disabled would mean a specific annotation is required to enable authorization per class.
1. Add, or us an existing, annotation that marks a class as authorized.

**Comment by kdubb** [comment]
I've logged an error during application build/start when Quarkus REST (aka RESTEasy Reactive) or RESTEasy (Classic)

**Comment by kdubb** [comment]
Both of these are implemented:
* Configuration - `quarkus.zanzibar.filter.enabled=false` disabled the filter
* Annotation - `@FGARelation(FGARelation.ANY)` on a class/method will selectively disable to the filter.
