### ISSUE TITLE
How to configure the credentials for the openFGA server

### ISSUE THREAD

**Issue by Plawn** [quarkiverse/quarkus-zanzibar#93]
Hello, 

I wanted to use this extension in my project to work with an openFGA server but the only properties I found are these one:

- quarkus.zanzibar.filter.enabled
- quarkus.zanzibar.filter.deny-unannotated-resource-methods
- quarkus.zanzibar.filter.unauthenticated-user
- quarkus.zanzibar.filter.timeout

And I can't find how to setup the url and secrets for the openFGA server

Can you help me ? or point me to the correct item of documentation

**Comment by kdubb** [comment]
https://docs.quarkiverse.io/quarkus-zanzibar/dev/index.html#_installation

OpenFGA properties are on the OpenFGA connector.

**Comment by Plawn** [comment]
Thanks !
