### ISSUE TITLE
Incorrect example ?

### ISSUE THREAD

**Issue by Plawn** [quarkiverse/quarkus-zanzibar#94]
Hello !

Thanks for your work !
I am trying to use your extension but I encountered some issues, with your example I have an error:
```
Caused by: io.quarkiverse.openfga.client.model.FGAValidationException: Invalid tuple 'thing:1#owner@1'. Reason: the 'user' field must be an object (e.g. document:1) or an 'object#relation' or a typed wildcard (e.g. group:*)
```

by chaning this [line](https://github.com/quarkiverse/quarkus-zanzibar/blob/main/docs/modules/ROOT/examples/ThingResource.java#L33) and  after reading the documentation and replacing `principal.getName()` with `"user:"+principal.getName()` It works.

Is there something I'm missing ?

**Comment by kdubb** [comment]
Your fix is correct. OpenFGA schema has changed since the example was written and it hasn't been updated correctly.

**Comment by kdubb** [comment]
Feel free to open a PR!
